### ISSUE TITLE
think about using redis for caching query results

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#47]
see http://www.memcached.org/

simple option to cache query/score results on the server side

**Comment by sgratzl** [comment]
or redis, since it seems to outperform memcached for larger data files

**Comment by sgratzl** [comment]
for the deployment this should be a pure volatile redis database. If mixed the the default one used for mapping all the volatile cache content will be persisted, too. 

see also https://github.com/phovea/phovea_data_redis/tree/redis_cache
and https://github.com/Caleydo/ordino/tree/cache

**Comment by sgratzl** [comment]
to locally use a different redis database. 

in `<workspace>/config.json`
```
"phovea_data_redis": {
    "cache": {
      "hostname": "redis_cache",
      "timeout": 6000
    }
  }
```
6000 = 6000sec = 100min

in `<workspace>/docker-compose.yml`
```
  db_redis_cache:
    image: 'redis:3.2-alpine'
    command: 'redis-server --save "" --appendonly no'
 ...
 api:  
    depends_on:
      - db_redis_cache
    links:
      - 'db_redis_cache:redis_cache'
```
